### ISSUE TITLE
Cookbook failure on libatomic_ops on RHEL7

### ISSUE THREAD

**Issue by ealliaume** [3scale/chef-3scale#2]
Got an error when using this cookbook.
It fails to install the package "libatomic_ops-devel" declared in openresty/recipes/commons_build.rb

Installed on ec2 with the AMI "Red Hat Enterprise Linux 7.2 (HVM), SSD Volume Type - ami-e0c19f83"

    Chef::Exceptions::Package
    -------------------------
    No candidate version available for libatomic_ops-devel

   yum_package("libatomic_ops-devel") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      package_name "libatomic_ops-devel"
      flush_cache {:before=>false, :after=>false}
      declared_type :package
      cookbook_name :openresty
      recipe_name "commons_build"
    end

**Comment by vdel26** [comment]
RHEL is not currently one of the [supported platforms](https://github.com/3scale/chef-3scale#supported-platforms). The only reason for that is that it's not guaranteed to be supported by the main dependency: the [chef-openresty](https://github.com/priestjim/chef-openresty#platform) cookbook.

The error you have hit is actually in the **chef-openresty** cookbook, so I encourage you to open an issue [there](https://github.com/priestjim/chef-openresty/issues). Once they include it in their supported versions, we will be able to do the same.
